# Funding platforms for VIBEE
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [gHashTag]
# patreon: vibee
# open_collective: vibee
# ko_fi: vibee
# custom: ["https://vibee-lang.dev/donate"]
