# ‚õìÔ∏è GOLDEN CHAIN - AIDER CONFIG

# Read these files for context
read:
  - CLAUDE.md
  - AGENTS.md
  - .cursorrules

# System prompt addition
extra-system-prompt: |
  ## ‚õî FORBIDDEN TO CREATE:
  - *.html (except runtime/runtime.html)
  - *.css, *.js, *.ts, *.jsx, *.tsx
  - *.zig in trinity/output/ (GENERATED ONLY!)
  - *.py (GENERATED ONLY!)

  ## ‚úÖ THE ONLY WAY TO WRITE CODE:
  1. Create .vibee specification in specs/tri/
  2. Run: ./bin/vibee gen specs/tri/feature.vibee
  3. Test: zig test trinity/output/feature.zig
  4. Write TOXIC VERDICT (self-criticism)
  5. Propose 3 options from TECH TREE

  ## üî• AFTER EVERY TASK:
  - TOXIC VERDICT: what done, what failed, self-criticism, score X/10
  - TECH TREE SELECT: 3 options [A/B/C] with recommendation

  ## œÜ¬≤ + 1/œÜ¬≤ = 3 | KOSCHEI IS IMMORTAL

# Lint command for .vibee files
lint-cmd:
  vibee: "python3 -c \"import yaml; yaml.safe_load(open('$FILE'))\""

# Auto commits off - manual control
auto-commits: false
