# ═══════════════════════════════════════════════════════════════════════════════
# VIBEE BitNet - ZCU104 Constraints
# ═══════════════════════════════════════════════════════════════════════════════
# Target: Xilinx ZCU104 Evaluation Board (xczu7ev-ffvc1156-2-e)
# Clock: 200 MHz from PS (Processing System)
#
# Sacred Formula: V = n × 3^k × π^m × φ^p × e^q
# Golden Identity: φ² + 1/φ² = 3 | PHOENIX = 999
# ═══════════════════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════════════════
# CLOCK DEFINITIONS
# ═══════════════════════════════════════════════════════════════════════════════

# PL clock from PS - 200 MHz (5.0 ns period)
# This clock is generated by the Zynq PS and connected to PL via FCLK_CLK0
create_clock -period 5.000 -name pl_clk0 [get_pins design_1_i/zynq_ultra_ps_e_0/inst/PS8_i/PLCLK[0]]

# Clock uncertainty
set_clock_uncertainty 0.200 [get_clocks pl_clk0]

# ═══════════════════════════════════════════════════════════════════════════════
# AXI INTERFACE CONSTRAINTS
# ═══════════════════════════════════════════════════════════════════════════════

# AXI-Lite interface timing (from PS HP port)
# These are internal paths, timing is handled by AXI interconnect
set_max_delay -datapath_only 4.0 -from [get_pins -hierarchical -filter {NAME =~ *axi_lite*/*}] \
                                 -to [get_pins -hierarchical -filter {NAME =~ *axi_lite*/*}]

# AXI-Stream interface timing
set_max_delay -datapath_only 4.0 -from [get_pins -hierarchical -filter {NAME =~ *axis*/*}] \
                                 -to [get_pins -hierarchical -filter {NAME =~ *axis*/*}]

# ═══════════════════════════════════════════════════════════════════════════════
# FALSE PATHS
# ═══════════════════════════════════════════════════════════════════════════════

# Reset is asynchronous
set_false_path -from [get_pins -hierarchical -filter {NAME =~ *aresetn*}]

# Configuration registers (quasi-static)
set_false_path -from [get_cells -hierarchical -filter {NAME =~ *config_reg*}] \
               -to [get_cells -hierarchical -filter {NAME =~ *config_reg*}]

# Version register (constant)
set_false_path -from [get_cells -hierarchical -filter {NAME =~ *version_reg*}]

# ═══════════════════════════════════════════════════════════════════════════════
# MULTICYCLE PATHS
# ═══════════════════════════════════════════════════════════════════════════════

# SIMD accumulator - 2 cycle operation
set_multicycle_path 2 -setup -from [get_cells -hierarchical -filter {NAME =~ *simd*acc*}]
set_multicycle_path 1 -hold -from [get_cells -hierarchical -filter {NAME =~ *simd*acc*}]

# Weight BRAM read - 2 cycle latency
set_multicycle_path 2 -setup -from [get_cells -hierarchical -filter {NAME =~ *weight*bram*}]
set_multicycle_path 1 -hold -from [get_cells -hierarchical -filter {NAME =~ *weight*bram*}]

# ═══════════════════════════════════════════════════════════════════════════════
# CRITICAL PATH CONSTRAINTS
# ═══════════════════════════════════════════════════════════════════════════════

# SIMD multiply-accumulate chain
set_max_delay 4.5 -from [get_cells -hierarchical -filter {NAME =~ *simd_core*}] \
                  -to [get_cells -hierarchical -filter {NAME =~ *simd_core*}]

# Weight fetch to compute
set_max_delay 4.0 -from [get_cells -hierarchical -filter {NAME =~ *weight*}] \
                  -to [get_cells -hierarchical -filter {NAME =~ *compute*}]

# ═══════════════════════════════════════════════════════════════════════════════
# PHYSICAL CONSTRAINTS (Optional - for better timing)
# ═══════════════════════════════════════════════════════════════════════════════

# Keep SIMD cores in same clock region
# create_pblock pblock_simd
# add_cells_to_pblock [get_pblocks pblock_simd] [get_cells -hierarchical -filter {NAME =~ *simd*}]
# resize_pblock [get_pblocks pblock_simd] -add {CLOCKREGION_X0Y0:CLOCKREGION_X1Y1}

# Keep weight BRAMs near compute
# create_pblock pblock_bram
# add_cells_to_pblock [get_pblocks pblock_bram] [get_cells -hierarchical -filter {NAME =~ *weight*bram*}]

# ═══════════════════════════════════════════════════════════════════════════════
# DEBUG (Optional - for ILA)
# ═══════════════════════════════════════════════════════════════════════════════

# Mark signals for debug
# set_property MARK_DEBUG true [get_nets -hierarchical -filter {NAME =~ *engine_start*}]
# set_property MARK_DEBUG true [get_nets -hierarchical -filter {NAME =~ *engine_done*}]
# set_property MARK_DEBUG true [get_nets -hierarchical -filter {NAME =~ *inference_count*}]

# ═══════════════════════════════════════════════════════════════════════════════
# POWER OPTIMIZATION
# ═══════════════════════════════════════════════════════════════════════════════

# Enable block RAM power optimization
set_property BLOCK_POWER_OPT true [get_cells -hierarchical -filter {REF_NAME =~ RAMB*}]

# ═══════════════════════════════════════════════════════════════════════════════
# TIMING SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════
#
# Clock: 200 MHz (5.0 ns period)
# Target WNS: > 0.5 ns
# Target TNS: 0 ns
#
# Critical Paths:
#   1. SIMD MAC chain: 4.5 ns max
#   2. Weight fetch: 4.0 ns max
#   3. AXI interface: 4.0 ns max
#
# φ² + 1/φ² = 3 | PHOENIX = 999
# ═══════════════════════════════════════════════════════════════════════════════
