// Integration tests for VIBEE Dogfooding System

import gleeunit
import gleeunit/should
import honeycomb/dogfooding/scanner
import honeycomb/dogfooding/autofix
import honeycomb/dogfooding/hooks
import honeycomb/dogfooding/watcher

pub fn main() {
  gleeunit.main()
}

// Scanner tests
pub fn scanner_default_config_test() {
  let config = scanner.default_scan_config()
  config.auto_fix
  |> should.equal(False)
}

pub fn scanner_is_generated_file_test() {
  let content = "// Generated by vibeec from spec.vibee\npub fn test() { Ok(42) }"
  scanner.is_generated_file(content)
  |> should.equal(True)
}

pub fn scanner_is_not_generated_file_test() {
  let content = "// Manual implementation\npub fn test() { Ok(42) }"
  scanner.is_generated_file(content)
  |> should.equal(False)
}

pub fn scanner_format_violation_test() {
  let violation =
    scanner.Violation(
      rule: scanner.NoManualCode,
      file_path: "test.gleam",
      line_number: 10,
      severity: scanner.Error,
      message: "Manual code detected",
      auto_fixable: True,
    )

  let formatted = scanner.format_violation(violation)
  formatted
  |> should.equal("ERROR: test.gleam:10 - Manual code detected")
}

// Autofix tests
pub fn autofix_default_config_test() {
  let config = autofix.default_fix_config()
  config.create_backups
  |> should.equal(True)
}

pub fn autofix_can_auto_fix_test() {
  let violation =
    scanner.Violation(
      rule: scanner.NoManualCode,
      file_path: "test.gleam",
      line_number: 1,
      severity: scanner.Error,
      message: "Test",
      auto_fixable: True,
    )

  autofix.can_auto_fix(violation)
  |> should.equal(True)
}

pub fn autofix_cannot_auto_fix_test() {
  let violation =
    scanner.Violation(
      rule: scanner.MissingSpec,
      file_path: "test.gleam",
      line_number: 1,
      severity: scanner.Warning,
      message: "Test",
      auto_fixable: False,
    )

  autofix.can_auto_fix(violation)
  |> should.equal(False)
}

// Hooks tests
pub fn hooks_is_git_repo_test() {
  // This will pass in the actual repo
  hooks.is_git_repo(".")
  |> should.equal(True)
}

pub fn hooks_get_hooks_dir_test() {
  let hooks_dir = hooks.get_hooks_dir(".")
  hooks_dir
  |> should.equal("./.git/hooks")
}

pub fn hooks_pre_commit_script_test() {
  let script = hooks.create_pre_commit_script()
  script
  |> should.not_equal("")
}

pub fn hooks_pre_push_script_test() {
  let script = hooks.create_pre_push_script()
  script
  |> should.not_equal("")
}

// Watcher tests
pub fn watcher_default_config_test() {
  let config = watcher.default_config()
  config.path
  |> should.equal("honeycomb/")
}

pub fn watcher_is_gleam_file_test() {
  watcher.is_gleam_file("test.gleam")
  |> should.equal(True)
}

pub fn watcher_is_not_gleam_file_test() {
  watcher.is_gleam_file("test.md")
  |> should.equal(False)
}

pub fn watcher_is_in_honeycomb_test() {
  watcher.is_in_honeycomb("honeycomb/test.gleam")
  |> should.equal(True)
}

pub fn watcher_is_not_in_honeycomb_test() {
  watcher.is_in_honeycomb("gleam/src/test.gleam")
  |> should.equal(False)
}

pub fn watcher_is_build_artifact_test() {
  watcher.is_build_artifact("build/dev/erlang/test.beam")
  |> should.equal(True)
}

pub fn watcher_is_not_build_artifact_test() {
  watcher.is_build_artifact("honeycomb/test.gleam")
  |> should.equal(False)
}

// Integration test: Full scan workflow
pub fn integration_scan_workflow_test() {
  let config = scanner.default_scan_config()

  // This should not crash
  let _result = scanner.scan_directory("honeycomb/dogfooding/", config)

  True
  |> should.equal(True)
}

// Integration test: Watcher initialization
pub fn integration_watcher_init_test() {
  let config = watcher.default_config()

  case watcher.start_watcher(config) {
    Ok(state) -> {
      state.config.path
      |> should.equal("honeycomb/")
    }
    Error(_) -> {
      // Should not fail
      True
      |> should.equal(False)
    }
  }
}
